### PR TITLE
Add example of BentoML with RedisAI

### PR DESCRIPTION
**Pull request by viettel-solutions**
Add example deploy ML models to RedisAI with BentoML.  [#1228](https://github.com/bentoml/BentoML/issues/1228)

Ideas based on: https://github.com/RedisAI/mlflow-redisai

### CODE REVIEW

**Comment by yubozhao** [comment]
This is great. @viettel-solutions Thank you for the example!

**Comment by viettel-solutions** [comment]
Hi @yubozhao,

Thank you so much for your nice words. I hope it helps. I cannot wait for future contribute in BentoML community.

Thanks,
- Viettel Solutions

**Comment by yubozhao** [comment]
@viettel-solutions your PR definitely helps!  It shows the community how to work with RedisAI.  It is very valuable.

We can't wait for the `1.0` release. It will makes bentoml a lot more easier to use.  Looking forward to see how it will changes with RedisAI.

**Comment by viettel-solutions** [comment]
Hi @yubozhao,

You just made my day!!! Thank you so so much. I cannot wait for the 1.0 release as well. I am glad to become a part of this community.

Many thanks,
- Viettel Solutions

**Pull request merged**
