### PR TITLE
Adding paddlepaddle materials to pair with paddlepaddle functionality being added to BentoML

### PR DESCRIPTION
**Pull request by deehrlic**
- Adding paddlepaddle materials as part of MLH Fellowship contribution

- Notebook should be in order save for links that point to things in the main repo related to the PR 

- Files modified are example notebook, a sample input file, and the README

### CODE REVIEW

**Comment by yubozhao** [comment]
@deehrlic Make sure resolve the conflict for README file

**Comment by deehrlic** [comment]
Resolved merge and added what I think the links will end up being for source/nbviewer etc., last change should be the import in the notebook, will change once we know Chau's PR is in and working

**Comment by deehrlic** [comment]
made the change to the notebook itself regarding import statement, whole thing should be good to go unless I missed something

**Comment by yubozhao** [comment]
@deehrlic I think we need to update the notebook with the new naming, `PaddlepaddleModelArtifact` and we can merge the PR afterward

**Comment by deehrlic** [comment]
@yubozhao tried to catch them all, let me know if I missed any name changes

**Pull request merged**
