### PR TITLE
Sample notebooks rc0

### PR DESCRIPTION
**Pull request by Mahima-ai**
This PR consists of examples for Bentoml V1.0.0-rc0 for Pytorch, Keras and HuggingFace Transformer Pipeline Frameworks.

### CODE REVIEW

**Comment by timliubentoml** [comment]
Hi @Mahima-ai! Will test it out tomorrow. Looks great!

**Comment by timliubentoml** [comment]
The Pytorch notebook looks like it works. But the other 2 are having issues with installing the dependencies. I'm on an m1 mac testing which maybe the issue because it looks like you're using tensorflow. What OS are you testing this with?
Screen Shot 2022-06-13 at 7 42 33 PM
Screen Shot 2022-06-13 at 7 40 26 PM

**Comment by Mahima-ai** [comment]
Hi @timliubentoml! I tested on ubuntu 20.04.1. For mac OS, tensorflow2 requirements listed [here](https://www.tensorflow.org/install/pip#macos) are:
1. macOS 10.12.6 (Sierra) or higher (64-bit) (no GPU support)
2. pip>20.3

**Comment by aarnphm** [comment]
same comments as #122

**Pull request closed without merging**
